---

- hosts: all
  gather_facts: true
  become: true

  pre_tasks:
    - import_tasks: includes/version.yml
    - name: Install packages
      apt:
        pkg:
          - acl
          - htop
          - gpg
          - python3-psycopg2
          - "{{ java_package }}"
        update_cache: true
      tags:
        - apt
    - name: Create .pgpass
      template:
        src: templates/pgpass.j2
        dest: /root/.pgpass
        mode: 0600
      tags:
        - db
        - postgres

  roles:
    - role: swap
      tags: ['never', 'swap']
    - role: postgresql
      tags: ['db', 'postgres']
    - role: elasticsearch
      tags: ['es', 'search']
    - role: collectionspace
      tags: ['collectionspace', 'cspace']
    - role: nginx
      tags: ['nginx', 'web']
    - role: certbot
      tags: ['certbot', 'certs']
      when: certbot_certs | length > 0

  tasks:
    - name: Create CollectionSpace vhost config
      template:
        src: templates/cspace.conf.j2
        dest: "/etc/nginx/sites-enabled/cspace.conf"
        mode: 0644
      notify: reload nginx
      tags:
        - nginx
        - vhost
        - web

    # TODO: initialize reports

    # do this last to minimize wait on startup initialization
    - name: Check that CollectionSpace is up before exiting
      uri:
        # bypass proxy, go straight to tomcat
        url: "http://127.0.0.1:8180/cspace/{{ collectionspace_tenant }}/login"
        method: GET
        status_code: 200
      register: result
      until: result.status == 200
      retries: 15
      delay: 60
