---

collections:
- name: community.general
  version: latest
  source: https://galaxy.ansible.com

roles:
- src: https://github.com/geerlingguy/ansible-role-certbot.git
  name: certbot
  version: 5.0.1

- src: https://github.com/geerlingguy/ansible-role-elasticsearch
  name: elasticsearch
  version: 5.1.0

- src: https://github.com/geerlingguy/ansible-role-nginx
  name: nginx
  version: 3.1.1

- src: https://github.com/geerlingguy/ansible-role-postgresql
  name: postgresql
  version: 3.2.1

- src: https://github.com/geerlingguy/ansible-role-swap
  name: swap
  version: 1.0.2