---

- name: Set CollectionSpace security options
  hosts: all
  gather_facts: true
  become: true

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted

  pre_tasks:
    - import_tasks: includes/version.yml
    - import_tasks: includes/security.yml
      tags:
        - security
