---

- name: Install packages
  apt:
    pkg:
      - ant
      - curl
      - git
      - imagemagick
      - maven
      - openjdk-8-jdk-headless
      - openjdk-8-jre-headless
      - python3-psycopg2
      - wget
    update_cache: true

- name: Create CollectionSpace directories
  file:
    path: "/opt/collectionspace/{{ item }}"
    owner: collectionspace
    group: collectionspace
    state: directory
    mode: '0755'
  with_items:
    - build
    - browser

- name: Transfer casts SQL to server
  copy:
    src: casts.sql
    dest: /root/casts.sql
    mode: '0644'
  register: casts

- name: Setup datatype casts
  community.postgresql.postgresql_script:
    db: template1
    login_host: localhost
    login_user: csadmin
    login_password: "{{ collectionspace_csadmin_password }}"
    path: /root/casts.sql
  when: casts.changed
