---

- name: Ensure the universe repository is present
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - "deb http://us.archive.ubuntu.com/ubuntu jammy universe"
    - "deb http://us.archive.ubuntu.com/ubuntu jammy-updates universe"
    - "deb http://security.ubuntu.com/ubuntu jammy-security universe"

- name: Update and upgrade apt packages
  apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 86400

- name: Install packages
  apt:
    pkg:
      - fail2ban
      - ufw
      - unattended-upgrades

- name: Enable periodic updates
  copy:
    src: 10periodic
    dest: /etc/apt/apt.conf.d/10periodic
    owner: root
    group: root
    mode: '0644'
